### ISSUE TITLE
support for Windows

### ISSUE THREAD

**Issue by blaugold** [cbl-dart/cbl-dart#24]
## Todo

- [ ] Setup building of windows libraries
- [ ] Add windows platform to `cbl_native`
- [ ] Add windows platform to `cbl_flutter`
- [ ] CI: Build libraries
- [ ] CI: Standalone Dart Tests
- [ ] CI: Flutter tests
- [ ] CD: Build and add libraries to release
- [ ] Add windows as supported platform to `cbl` README

**Comment by blaugold** [comment]
Progress for Windows support is now being tracked in https://github.com/cbl-dart/cbl-dart/projects/5
